CC = g++
2-1.o: 2-1.cpp linked_list.cpp
	$(CC) -o $@ $^

2-2.o: 2-2.cpp linked_list.cpp
	$(CC) -o $@ $^

2-3.o: 2-3.cpp linked_list.cpp
	$(CC) -o $@ $^ 

2-4.o: 2-4.cpp linked_list.cpp
	$(CC) -o $@ $^

2-5.o: 2-5.cpp linked_list.cpp
	$(CC) -o $@ $^

2-6.o: 2-6.cpp linked_list.cpp
	$(CC) -o $@ $^

2-7.o: 2-7.cpp linked_list.cpp
	$(CC) -o $@ $^
